p='index.html';s=open(p).read()
s=s.replace('<html lang="en">','<html lang="pt-BR">').replace('<title>Base44 APP</title>','<title>Gerador de Pseudociências · Dr. Charles Latão</title>\n    <meta name="description" content="Gere sua pseudociência personalizada com a ajuda do Doutor Charles Latão. Uma sátira educativa de André D. Bacchi." />')
s=s.replace('<link rel="icon" type="image/svg+xml" href="https://base44.com/logo_v2.svg" />','<link rel="icon" type="image/png" href="./icons/favicon-64.png" />\n    <link rel="apple-touch-icon" href="./icons/apple-touch-icon.png" />\n    <meta name="theme-color" content="#0c0c0e" />\n    <meta name="apple-mobile-web-app-capable" content="yes" />\n    <meta name="apple-mobile-web-app-title" content="Pseudociências" />')
s=s.replace('href="/manifest.json"','href="./manifest.json"')
s=s.replace('</body>','  <script>if("serviceWorker" in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));}</script>\n  </body>')
open(p,'w').write(s)
